// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// SearchBrakes - Use 'SearchBrakesParams' to pass parameters into this method.
        /// </summary>
        public void SearchBrakes()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UINewtabInternetExplorWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            WinMenuItem uIPasteMenuItem = this.UIItemWindow.UIContextMenu.UIPasteMenuItem;
            WinButton uIGotohttpspupsiazurewButton = this.UINewtabInternetExplorWindow.UIPageControlToolBar.UIGotohttpspupsiazurewButton;
            HtmlEdit uIQEdit = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UIQEdit;
            HtmlInputButton uISearchButton = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UISearchButton;
            #endregion

            // Click 'Address and search using Bing' text box
            Mouse.Click(uIAddressandsearchusinEdit, new Point(120, 8));

            // Right-Click 'Address and search using Bing' text box
            Mouse.Click(uIAddressandsearchusinEdit, MouseButtons.Right, ModifierKeys.None, new Point(121, 7));

            // Click 'Paste' menu item
            Mouse.Click(uIPasteMenuItem, new Point(45, 8));

            // Click 'Go to “https://pupsi.azurewebsites.net/” (Alt+Ente...' button
            Mouse.Click(uIGotohttpspupsiazurewButton, new Point(8, 13));

            // Type 'brakes' in 'q' text box
            uIQEdit.Text = this.SearchBrakesParams.UIQEditText;

            // Set flag to allow play back to continue if non-essential actions fail. (For example, if a mouse hover action fails.)
            Playback.PlaybackSettings.ContinueOnError = true;

            // Mouse hover 'q' text box at (1, 1)
            Mouse.Hover(uIQEdit, new Point(1, 1));

            // Reset flag to ensure that play back stops if there is an error.
            Playback.PlaybackSettings.ContinueOnError = false;

            // Click 'Search' button
            Mouse.Click(uISearchButton, new Point(15, 27));
        }
        
        /// <summary>
        /// SearchParts - Use 'SearchPartsParams' to pass parameters into this method.
        /// </summary>
        public void SearchParts()
        {
            #region Variable Declarations
            HtmlEdit uIQEdit = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UIQEdit;
            HtmlInputButton uISearchButton = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UISearchButton;
            HtmlHyperlink uIHomeHyperlink = this.UINewtabInternetExplorWindow.UIPartsUnlimitedDocument.UIHomeHyperlink;
            HtmlHyperlink uIHomeHyperlink1 = this.UINewtabInternetExplorWindow.UIPartsUnlimitedDocument1.UIHomeHyperlink;
            HtmlImage uIHalogenHeadlights2PaImage = this.UINewtabInternetExplorWindow.UIPartsUnlimitedDocument2.UISearchpageCustom.UIHalogenHeadlights2PaImage;
            #endregion

            // Type 'tyre' in 'q' text box
            uIQEdit.Text = this.SearchPartsParams.UIQEditText;

            // Click 'Search' button
            Mouse.Click(uISearchButton, new Point(20, 23));

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink, new Point(21, 17));

            // Type 'bolt' in 'q' text box
            uIQEdit.Text = this.SearchPartsParams.UIQEditText1;

            // Click 'Search' button
            Mouse.Click(uISearchButton, new Point(24, 31));

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink1, new Point(17, 30));

            // Type 'light' in 'q' text box
            uIQEdit.Text = this.SearchPartsParams.UIQEditText2;

            // Click 'Search' button
            Mouse.Click(uISearchButton, new Point(22, 31));

            // Click 'Halogen Headlights (2 Pack) zoom' image
            Mouse.Click(uIHalogenHeadlights2PaImage, new Point(211, 191));
        }
        
        /// <summary>
        /// VerifyMenuOptions
        /// </summary>
        public void VerifyMenuOptions()
        {
            #region Variable Declarations
            HtmlHyperlink uIBrakesHyperlink = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UIBrakesHyperlink;
            HtmlHyperlink uIHomeHyperlink = this.UINewtabInternetExplorWindow.UIBrowseProductsPartsUDocument.UIHomeHyperlink;
            HtmlHyperlink uILightingHyperlink = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UILightingHyperlink;
            HtmlHyperlink uIHomeHyperlink1 = this.UINewtabInternetExplorWindow.UIBrowseProductsPartsUDocument1.UIHomeHyperlink;
            HtmlHyperlink uIWheelsTiresHyperlink = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UIWheelsTiresHyperlink;
            HtmlHyperlink uIHomeHyperlink2 = this.UINewtabInternetExplorWindow.UIBrowseProductsPartsUDocument2.UIHomeHyperlink;
            HtmlHyperlink uIBatteriesHyperlink = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UIBatteriesHyperlink;
            #endregion

            // Click 'Brakes' link
            Mouse.Click(uIBrakesHyperlink, new Point(31, 18));

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink, new Point(19, 14));

            // Click 'Lighting' link
            Mouse.Click(uILightingHyperlink, new Point(29, 16));

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink1, new Point(29, 33));

            // Click 'Wheels & Tires' link
            Mouse.Click(uIWheelsTiresHyperlink, new Point(68, 13));

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink2, new Point(22, 38));

            // Click 'Batteries' link
            Mouse.Click(uIBatteriesHyperlink, new Point(23, 16));
        }
        

        /// <summary>
        /// RegiesterNewUser - Use 'RegiesterNewUserParams' to pass parameters into this method.
        /// </summary>
        public void RegiesterNewUser()
        {
            #region Variable Declarations
            HtmlHyperlink uILoginHyperlink = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UILoginHyperlink;
            HtmlHyperlink uIRegisterasanewuserHyperlink = this.UINewtabInternetExplorWindow.UILoginPartsUnlimitedDocument.UILoginpanelPane.UIRegisterasanewuserHyperlink;
            HtmlEdit uIEmailEdit = this.UINewtabInternetExplorWindow.UIRegisterPartsUnlimitDocument.UIEmailEdit;
            HtmlEdit uIPasswordEdit = this.UINewtabInternetExplorWindow.UIRegisterPartsUnlimitDocument.UIPasswordEdit;
            HtmlEdit uIConfirmPasswordEdit = this.UINewtabInternetExplorWindow.UIRegisterPartsUnlimitDocument.UIConfirmPasswordEdit;
            HtmlInputButton uIRegisterButton = this.UINewtabInternetExplorWindow.UIRegisterPartsUnlimitDocument.UIRegisterpageCustom.UIRegisterButton;
            #endregion

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(18, 23));

            // Click 'Register as a new user' link
            Mouse.Click(uIRegisterasanewuserHyperlink, new Point(71, 10));

            // Type 'charan.4u22@gmail.com' in 'Email' text box
            uIEmailEdit.Text = this.RegiesterNewUserParams.UIEmailEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.RegiesterNewUserParams.UIPasswordEditPassword;

            // Type '********' in 'ConfirmPassword' text box
            uIConfirmPasswordEdit.Password = this.RegiesterNewUserParams.UIConfirmPasswordEditPassword;

            // Click 'Register' button
            Mouse.Click(uIRegisterButton, new Point(64, 19));
        }
        
        /// <summary>
        /// LoginUser1 - Use 'LoginUser1Params' to pass parameters into this method.
        /// </summary>
        public void LoginUser1()
        {
            #region Variable Declarations
            HtmlHyperlink uILoginHyperlink = this.UINewtabInternetExplorWindow.UIHomePagePartsUnlimitDocument.UILoginHyperlink;
            HtmlEdit uIEmailEdit = this.UINewtabInternetExplorWindow.UILoginPartsUnlimitedDocument.UIEmailEdit;
            HtmlEdit uIPasswordEdit = this.UINewtabInternetExplorWindow.UILoginPartsUnlimitedDocument.UIPasswordEdit;
            HtmlInputButton uILoginButton = this.UINewtabInternetExplorWindow.UILoginPartsUnlimitedDocument.UILoginpanelPane.UILoginButton;
            #endregion

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(21, 36));

            // Click 'Log in' link
            Mouse.Click(uILoginHyperlink, new Point(31, 43));

            // Type 'charan.4u22@gmail.com' in 'Email' text box
            uIEmailEdit.Text = this.LoginUser1Params.UIEmailEditText;

            // Type '' in 'Password' text box
            uIPasswordEdit.Text = this.LoginUser1Params.UIPasswordEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LoginUser1Params.UIPasswordEditPassword;

            // Click 'Login' button
            Mouse.Click(uILoginButton, new Point(56, 26));
        }
        

        #region Properties
        public virtual SearchBrakesParams SearchBrakesParams
        {
            get
            {
                if ((this.mSearchBrakesParams == null))
                {
                    this.mSearchBrakesParams = new SearchBrakesParams();
                }
                return this.mSearchBrakesParams;
            }
        }
        
        public virtual SearchPartsParams SearchPartsParams
        {
            get
            {
                if ((this.mSearchPartsParams == null))
                {
                    this.mSearchPartsParams = new SearchPartsParams();
                }
                return this.mSearchPartsParams;
            }
        }
        

        public virtual RegiesterNewUserParams RegiesterNewUserParams
        {
            get
            {
                if ((this.mRegiesterNewUserParams == null))
                {
                    this.mRegiesterNewUserParams = new RegiesterNewUserParams();
                }
                return this.mRegiesterNewUserParams;
            }
        }
        
        public virtual LoginUser1Params LoginUser1Params
        {
            get
            {
                if ((this.mLoginUser1Params == null))
                {
                    this.mLoginUser1Params = new LoginUser1Params();
                }
                return this.mLoginUser1Params;
            }
        }
        

        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private SearchBrakesParams mSearchBrakesParams;
        
        private SearchPartsParams mSearchPartsParams;
        

        private RegiesterNewUserParams mRegiesterNewUserParams;
        
        private LoginUser1Params mLoginUser1Params;

        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        
        private UIItemWindow1 mUIItemWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SearchBrakes'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class SearchBrakesParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'brakes' in 'q' text box
        /// </summary>
        public string UIQEditText = "brakes";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SearchParts'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class SearchPartsParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'tyre' in 'q' text box
        /// </summary>
        public string UIQEditText = "tyre";
        
        /// <summary>
        /// Type 'bolt' in 'q' text box
        /// </summary>
        public string UIQEditText1 = "bolt";
        
        /// <summary>
        /// Type 'light' in 'q' text box
        /// </summary>
        public string UIQEditText2 = "light";
        #endregion
    }
    

    /// <summary>
    /// Parameters to be passed into 'RegiesterNewUser'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RegiesterNewUserParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'charan.4u22@gmail.com' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "charan.4u22@gmail.com";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "vK0aSlL2f8kWswmZ0ZG6DK0D9HO/5DtG";
        
        /// <summary>
        /// Type '********' in 'ConfirmPassword' text box
        /// </summary>
        public string UIConfirmPasswordEditPassword = "vK0aSlL2f8kWswmZ0ZG6DK0D9HO/5DtG";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginUser1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class LoginUser1Params
    {
        
        #region Fields
        /// <summary>
        /// Type 'charan.4u22@gmail.com' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "charan.4u22@gmail.com";
        
        /// <summary>
        /// Type '' in 'Password' text box
        /// </summary>
        public string UIPasswordEditText = "";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "vK0aSlL2f8kWswmZ0ZG6DK0D9HO/5DtG";
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("Home Page – Parts Unlimited");
            this.WindowTitles.Add("– Parts Unlimited");
            this.WindowTitles.Add("Browse Products – Parts Unlimited");

            this.WindowTitles.Add("Log in – Parts Unlimited");
            this.WindowTitles.Add("Register – Parts Unlimited");

            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIPageControlToolBar UIPageControlToolBar
        {
            get
            {
                if ((this.mUIPageControlToolBar == null))
                {
                    this.mUIPageControlToolBar = new UIPageControlToolBar(this);
                }
                return this.mUIPageControlToolBar;
            }
        }
        
        public UIHomePagePartsUnlimitDocument UIHomePagePartsUnlimitDocument
        {
            get
            {
                if ((this.mUIHomePagePartsUnlimitDocument == null))
                {
                    this.mUIHomePagePartsUnlimitDocument = new UIHomePagePartsUnlimitDocument(this);
                }
                return this.mUIHomePagePartsUnlimitDocument;
            }
        }
        
        public UIPartsUnlimitedDocument UIPartsUnlimitedDocument
        {
            get
            {
                if ((this.mUIPartsUnlimitedDocument == null))
                {
                    this.mUIPartsUnlimitedDocument = new UIPartsUnlimitedDocument(this);
                }
                return this.mUIPartsUnlimitedDocument;
            }
        }
        
        public UIPartsUnlimitedDocument1 UIPartsUnlimitedDocument1
        {
            get
            {
                if ((this.mUIPartsUnlimitedDocument1 == null))
                {
                    this.mUIPartsUnlimitedDocument1 = new UIPartsUnlimitedDocument1(this);
                }
                return this.mUIPartsUnlimitedDocument1;
            }
        }
        
        public UIPartsUnlimitedDocument2 UIPartsUnlimitedDocument2
        {
            get
            {
                if ((this.mUIPartsUnlimitedDocument2 == null))
                {
                    this.mUIPartsUnlimitedDocument2 = new UIPartsUnlimitedDocument2(this);
                }
                return this.mUIPartsUnlimitedDocument2;
            }
        }
        
        public UIBrowseProductsPartsUDocument UIBrowseProductsPartsUDocument
        {
            get
            {
                if ((this.mUIBrowseProductsPartsUDocument == null))
                {
                    this.mUIBrowseProductsPartsUDocument = new UIBrowseProductsPartsUDocument(this);
                }
                return this.mUIBrowseProductsPartsUDocument;
            }
        }
        
        public UIBrowseProductsPartsUDocument1 UIBrowseProductsPartsUDocument1
        {
            get
            {
                if ((this.mUIBrowseProductsPartsUDocument1 == null))
                {
                    this.mUIBrowseProductsPartsUDocument1 = new UIBrowseProductsPartsUDocument1(this);
                }
                return this.mUIBrowseProductsPartsUDocument1;
            }
        }
        
        public UIBrowseProductsPartsUDocument2 UIBrowseProductsPartsUDocument2
        {
            get
            {
                if ((this.mUIBrowseProductsPartsUDocument2 == null))
                {
                    this.mUIBrowseProductsPartsUDocument2 = new UIBrowseProductsPartsUDocument2(this);
                }
                return this.mUIBrowseProductsPartsUDocument2;
            }
        }

        
        public UILoginPartsUnlimitedDocument UILoginPartsUnlimitedDocument
        {
            get
            {
                if ((this.mUILoginPartsUnlimitedDocument == null))
                {
                    this.mUILoginPartsUnlimitedDocument = new UILoginPartsUnlimitedDocument(this);
                }
                return this.mUILoginPartsUnlimitedDocument;
            }
        }
        
        public UIRegisterPartsUnlimitDocument UIRegisterPartsUnlimitDocument
        {
            get
            {
                if ((this.mUIRegisterPartsUnlimitDocument == null))
                {
                    this.mUIRegisterPartsUnlimitDocument = new UIRegisterPartsUnlimitDocument(this);
                }
                return this.mUIRegisterPartsUnlimitDocument;
            }
        }

        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIAddressBarClient mUIAddressBarClient;
        
        private UIPageControlToolBar mUIPageControlToolBar;
        
        private UIHomePagePartsUnlimitDocument mUIHomePagePartsUnlimitDocument;
        
        private UIPartsUnlimitedDocument mUIPartsUnlimitedDocument;
        
        private UIPartsUnlimitedDocument1 mUIPartsUnlimitedDocument1;
        
        private UIPartsUnlimitedDocument2 mUIPartsUnlimitedDocument2;
        
        private UIBrowseProductsPartsUDocument mUIBrowseProductsPartsUDocument;
        
        private UIBrowseProductsPartsUDocument1 mUIBrowseProductsPartsUDocument1;
        
        private UIBrowseProductsPartsUDocument2 mUIBrowseProductsPartsUDocument2;

        
        private UILoginPartsUnlimitedDocument mUILoginPartsUnlimitedDocument;
        
        private UIRegisterPartsUnlimitDocument mUIRegisterPartsUnlimitDocument;

        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinClient UINewtabInternetExplorClient
        {
            get
            {
                if ((this.mUINewtabInternetExplorClient == null))
                {
                    this.mUINewtabInternetExplorClient = new WinClient(this);
                    #region Search Criteria
                    this.mUINewtabInternetExplorClient.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUINewtabInternetExplorClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUINewtabInternetExplorClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPageControlToolBar : WinToolBar
    {
        
        public UIPageControlToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Page Control";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinButton UIGotohttpspupsiazurewButton
        {
            get
            {
                if ((this.mUIGotohttpspupsiazurewButton == null))
                {
                    this.mUIGotohttpspupsiazurewButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIGotohttpspupsiazurewButton.SearchProperties[WinButton.PropertyNames.Name] = "Go to “https://pupsi.azurewebsites.net/” (Alt+Enter to open in a new tab)";
                    this.mUIGotohttpspupsiazurewButton.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIGotohttpspupsiazurewButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIGotohttpspupsiazurewButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePagePartsUnlimitDocument : HtmlDocument
    {
        
        public UIHomePagePartsUnlimitDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/";
            this.WindowTitles.Add("Home Page – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIQEdit
        {
            get
            {
                if ((this.mUIQEdit == null))
                {
                    this.mUIQEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIQEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "search-box";
                    this.mUIQEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "q";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"q\" class=\"form-control\" id=\"search";
                    this.mUIQEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIQEdit.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIQEdit;
            }
        }
        
        public HtmlInputButton UISearchButton
        {
            get
            {
                if ((this.mUISearchButton == null))
                {
                    this.mUISearchButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = "search-link";
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Search";
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = null;
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "id=\"search-link\" type=\"submit\" value=\"Se";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUISearchButton.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUISearchButton;
            }
        }
        
        public HtmlHyperlink UIBrakesHyperlink
        {
            get
            {
                if ((this.mUIBrakesHyperlink == null))
                {
                    this.mUIBrakesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBrakesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Brakes";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/Store/Browse?CategoryId=1";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=1\"";
                    this.mUIBrakesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "14";
                    this.mUIBrakesHyperlink.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIBrakesHyperlink;
            }
        }
        
        public HtmlHyperlink UILightingHyperlink
        {
            get
            {
                if ((this.mUILightingHyperlink == null))
                {
                    this.mUILightingHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILightingHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Lighting";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/Store/Browse?CategoryId=2";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=2\"";
                    this.mUILightingHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "15";
                    this.mUILightingHyperlink.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUILightingHyperlink;
            }
        }
        
        public HtmlHyperlink UIWheelsTiresHyperlink
        {
            get
            {
                if ((this.mUIWheelsTiresHyperlink == null))
                {
                    this.mUIWheelsTiresHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIWheelsTiresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIWheelsTiresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIWheelsTiresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIWheelsTiresHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Wheels & Tires";
                    this.mUIWheelsTiresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUIWheelsTiresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIWheelsTiresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/Store/Browse?CategoryId=3";
                    this.mUIWheelsTiresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIWheelsTiresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=3\"";
                    this.mUIWheelsTiresHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "16";
                    this.mUIWheelsTiresHyperlink.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIWheelsTiresHyperlink;
            }
        }
        
        public HtmlHyperlink UIBatteriesHyperlink
        {
            get
            {
                if ((this.mUIBatteriesHyperlink == null))
                {
                    this.mUIBatteriesHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBatteriesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBatteriesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBatteriesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBatteriesHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Batteries";
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Store/Browse";
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/Store/Browse?CategoryId=4";
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Store/Browse?CategoryId=4\"";
                    this.mUIBatteriesHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "17";
                    this.mUIBatteriesHyperlink.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUIBatteriesHyperlink;
            }
        }

        
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "login-link";
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Log in";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "head-link";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"head-link\" id=\"login-link\" href=\"";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "6";
                    this.mUILoginHyperlink.WindowTitles.Add("Home Page – Parts Unlimited");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }

        #endregion
        
        #region Fields
        private HtmlEdit mUIQEdit;
        
        private HtmlInputButton mUISearchButton;
        
        private HtmlHyperlink mUIBrakesHyperlink;
        
        private HtmlHyperlink mUILightingHyperlink;
        
        private HtmlHyperlink mUIWheelsTiresHyperlink;
        
        private HtmlHyperlink mUIBatteriesHyperlink;

        
        private HtmlHyperlink mUILoginHyperlink;

        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPartsUnlimitedDocument : HtmlDocument
    {
        
        public UIPartsUnlimitedDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "– Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Search";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/Search?q=tyre";
            this.WindowTitles.Add("– Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "home-link";
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "head-link";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"head-link\" id=\"home-link\" href=\"/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIHomeHyperlink.WindowTitles.Add("– Parts Unlimited");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPartsUnlimitedDocument1 : HtmlDocument
    {
        
        public UIPartsUnlimitedDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "– Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Search";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/Search?q=bolt";
            this.WindowTitles.Add("– Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "home-link";
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "head-link";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"head-link\" id=\"home-link\" href=\"/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIHomeHyperlink.WindowTitles.Add("– Parts Unlimited");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPartsUnlimitedDocument2 : HtmlDocument
    {
        
        public UIPartsUnlimitedDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "– Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Search";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/Search?q=light";
            this.WindowTitles.Add("– Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UISearchpageCustom UISearchpageCustom
        {
            get
            {
                if ((this.mUISearchpageCustom == null))
                {
                    this.mUISearchpageCustom = new UISearchpageCustom(this);
                }
                return this.mUISearchpageCustom;
            }
        }
        #endregion
        
        #region Fields
        private UISearchpageCustom mUISearchpageCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UISearchpageCustom : HtmlCustom
    {
        
        public UISearchpageCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "SECTION";
            this.SearchProperties["Id"] = "search-page";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "section-alt";
            this.FilterProperties["ControlDefinition"] = "class=\"section-alt\" id=\"search-page\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("– Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlImage UIHalogenHeadlights2PaImage
        {
            get
            {
                if ((this.mUIHalogenHeadlights2PaImage == null))
                {
                    this.mUIHalogenHeadlights2PaImage = new HtmlImage(this);
                    #region Search Criteria
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Id] = null;
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Name] = null;
                    this.mUIHalogenHeadlights2PaImage.SearchProperties[HtmlImage.PropertyNames.Alt] = "Halogen Headlights (2 Pack) zoom";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.AbsolutePath] = "/images/product_lighting_headlight.jpg";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Src] = "https://pupsi.azurewebsites.net/images/product_lighting_headlight.jpg";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.LinkAbsolutePath] = "/Store/Details/1";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Href] = "https://pupsi.azurewebsites.net/Store/Details/1";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.Class] = null;
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.ControlDefinition] = "alt=\"Halogen Headlights (2 Pack) zoom\" s";
                    this.mUIHalogenHeadlights2PaImage.FilterProperties[HtmlImage.PropertyNames.TagInstance] = "2";
                    this.mUIHalogenHeadlights2PaImage.WindowTitles.Add("– Parts Unlimited");
                    #endregion
                }
                return this.mUIHalogenHeadlights2PaImage;
            }
        }
        #endregion
        
        #region Fields
        private HtmlImage mUIHalogenHeadlights2PaImage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBrowseProductsPartsUDocument : HtmlDocument
    {
        
        public UIBrowseProductsPartsUDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Browse Products – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Browse";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/Store/Browse?CategoryId=1";
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "home-link";
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "head-link";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"head-link\" id=\"home-link\" href=\"/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIHomeHyperlink.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBrowseProductsPartsUDocument1 : HtmlDocument
    {
        
        public UIBrowseProductsPartsUDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Browse Products – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Browse";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/Store/Browse?CategoryId=2";
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "home-link";
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "head-link";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"head-link\" id=\"home-link\" href=\"/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIHomeHyperlink.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIBrowseProductsPartsUDocument2 : HtmlDocument
    {
        
        public UIBrowseProductsPartsUDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Browse Products – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Store/Browse";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/Store/Browse?CategoryId=3";
            this.WindowTitles.Add("Browse Products – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "home-link";
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "head-link";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"head-link\" id=\"home-link\" href=\"/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIHomeHyperlink.WindowTitles.Add("Browse Products – Parts Unlimited");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]

    public class UILoginPartsUnlimitedDocument : HtmlDocument
    {
        
        public UILoginPartsUnlimitedDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log in – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/Account/Login";
            this.WindowTitles.Add("Log in – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public UILoginpanelPane UILoginpanelPane
        {
            get
            {
                if ((this.mUILoginpanelPane == null))
                {
                    this.mUILoginpanelPane = new UILoginpanelPane(this);
                }
                return this.mUILoginpanelPane;
            }
        }
        
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"form-control\" id=\"Em";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUIEmailEdit.WindowTitles.Add("Log in – Parts Unlimited");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUIPasswordEdit.WindowTitles.Add("Log in – Parts Unlimited");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        #endregion
        
        #region Fields
        private UILoginpanelPane mUILoginpanelPane;
        
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUIPasswordEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILoginpanelPane : HtmlDiv
    {
        
        public UILoginpanelPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "login-panel";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Registered Customers\r\n\r\n \r\n\r\n\r\n  \r\n\r\n\r\n\r";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"login-panel\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "20";
            this.WindowTitles.Add("Log in – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIRegisterasanewuserHyperlink
        {
            get
            {
                if ((this.mUIRegisterasanewuserHyperlink == null))
                {
                    this.mUIRegisterasanewuserHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIRegisterasanewuserHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIRegisterasanewuserHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIRegisterasanewuserHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIRegisterasanewuserHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Register as a new user";
                    this.mUIRegisterasanewuserHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Account/Register";
                    this.mUIRegisterasanewuserHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIRegisterasanewuserHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://pupsi.azurewebsites.net/Account/Register";
                    this.mUIRegisterasanewuserHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "action-link";
                    this.mUIRegisterasanewuserHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"action-link\" href=\"/Account/Regis";
                    this.mUIRegisterasanewuserHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIRegisterasanewuserHyperlink.WindowTitles.Add("Log in – Parts Unlimited");
                    #endregion
                }
                return this.mUIRegisterasanewuserHyperlink;
            }
        }
        
        public HtmlInputButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Login";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUILoginButton.WindowTitles.Add("Log in – Parts Unlimited");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIRegisterasanewuserHyperlink;
        
        private HtmlInputButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRegisterPartsUnlimitDocument : HtmlDocument
    {
        
        public UIRegisterPartsUnlimitDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Register – Parts Unlimited";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Account/Register";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://pupsi.azurewebsites.net/Account/Register";
            this.WindowTitles.Add("Register – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"form-control\" id=\"Em";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUIEmailEdit.WindowTitles.Add("Register – Parts Unlimited");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUIPasswordEdit.WindowTitles.Add("Register – Parts Unlimited");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlEdit UIConfirmPasswordEdit
        {
            get
            {
                if ((this.mUIConfirmPasswordEdit == null))
                {
                    this.mUIConfirmPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIConfirmPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ConfirmPassword";
                    this.mUIConfirmPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ConfirmPassword";
                    this.mUIConfirmPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIConfirmPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIConfirmPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIConfirmPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIConfirmPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ConfirmPassword\" class=\"form-contr";
                    this.mUIConfirmPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUIConfirmPasswordEdit.WindowTitles.Add("Register – Parts Unlimited");
                    #endregion
                }
                return this.mUIConfirmPasswordEdit;
            }
        }
        
        public UIRegisterpageCustom UIRegisterpageCustom
        {
            get
            {
                if ((this.mUIRegisterpageCustom == null))
                {
                    this.mUIRegisterpageCustom = new UIRegisterpageCustom(this);
                }
                return this.mUIRegisterpageCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlEdit mUIConfirmPasswordEdit;
        
        private UIRegisterpageCustom mUIRegisterpageCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRegisterpageCustom : HtmlCustom
    {
        
        public UIRegisterpageCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "SECTION";
            this.SearchProperties["Id"] = "register-page";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"register-page\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Register – Parts Unlimited");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIRegisterButton
        {
            get
            {
                if ((this.mUIRegisterButton == null))
                {
                    this.mUIRegisterButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIRegisterButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIRegisterButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIRegisterButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Register";
                    this.mUIRegisterButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIRegisterButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIRegisterButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIRegisterButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUIRegisterButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "5";
                    this.mUIRegisterButton.WindowTitles.Add("Register – Parts Unlimited");
                    #endregion
                }
                return this.mUIRegisterButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIRegisterButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]

    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Context";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32768";
            #endregion
        }
        
        #region Properties
        public UIContextMenu UIContextMenu
        {
            get
            {
                if ((this.mUIContextMenu == null))
                {
                    this.mUIContextMenu = new UIContextMenu(this);
                }
                return this.mUIContextMenu;
            }
        }
        #endregion
        
        #region Fields
        private UIContextMenu mUIContextMenu;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIContextMenu : WinMenu
    {
        
        public UIContextMenu(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "Context";
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIPasteMenuItem
        {
            get
            {
                if ((this.mUIPasteMenuItem == null))
                {
                    this.mUIPasteMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIPasteMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Paste";
                    #endregion
                }
                return this.mUIPasteMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIPasteMenuItem;
        #endregion
    }
}
